### ISSUE TITLE
Select Web Frontend

### ISSUE THREAD

**Issue by the-maldridge** [BESTRobotics/registry#2]
We need to select a web frontend.  I personally am a fan of VueJS and Vuetify, since that gets us mobile versions for free, as well as native apps if we decided we ever wanted those.  I've used VueJS in the past and been happy with it, but its only a suggestion.  I have not tried to brand anything with it before.

This thread is to select what web frontend technology we should use.

**Comment by scauthen** [comment]
I do believe the site needs to be responsive so it will work on any screen resolution (mobile, tablet, computer), especially the page(s) that list the events. So many people use mobile devices these days when searching, it would be good to support this from the get-go.

**Comment by the-maldridge** [comment]
AngularJS is a pretty great framework, but unless you're referring to AngularJS-2 we are risking being marooned on an old version with no migration path.  VueJS was designed by the same principal engineer as the original Angular, so it should feel very familiar, but it has a publicly stated maintenance policy.  If you're instead referring to AngularJS-2 then this is a moot point, please disregard.

**Comment by scauthen** [comment]
I have used both 1.7.x and 2.x. I can do some learning on VueJS. I see it has an implementation of Bootstrap. I would prefer Bootstrap for the formatting as I’ve done quite a bit of responsive sites for mobile/pc with it. Yalls thoughts?

**Comment by scauthen** [comment]
Are we going to manage the front and backend in the same repo or separate ones?

**Comment by the-maldridge** [comment]
Lets do the same repo with whatever tech you feel most comfortable in.  Please plan to put your files in `web/`.

**Comment by scauthen** [comment]
I realize phase 1 is the registration system, but as I started developing a general idea for the “theme” it occurred to me we have both consume and administrator pages which will be created. Per the discussion of the total replacement of the dashboard (later phase), are we also looking to revamp the consumer side of the site. The reason for addressing this is that it would affect the overall /web folder structure. I plan to have common headers, footers, etc for consistancy. If this is just for registration, these “theme” files can live in that directory. If a future goal is to theme the entire consumer site the same, these files really need to live in the root. You alls thoughts.

**Comment by gdyoung93** [comment]
Agree completely. No attempt to sync. There is no need. Data in Wordpress
tables is not the same data as in this (or other) system.
Greg

**Comment by m-wynn** [comment]
If nobody has any major concerns, I'm most familiar with React and [Semantic UI](https://react.semantic-ui.com/).  Possibly Redux if the front-end data model gets big.  It'll optimize everything for a release build and webpack it up as well.

This would allow me to get something up super quickly without having to take time to learn a new technology, and also provides a pretty easy interface for custom theming.

**Comment by the-maldridge** [comment]
:shipit:
