### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by gdyoung93** [BESTRobotics/registry#44]
Need a "Forgot Password" option on the Login screen. This will happen many many times. It should be automated if possible so no one has to manage it.

**Comment by the-maldridge** [comment]
I'm planning to do this as a typical punch in your email and it mails you a link.  From that link it will send you a new password which ideally you would reset, but we don't have a way to do that just yet, so the reset password will live for quite a while.

**Comment by m-wynn** [comment]
Fixed in db9473694a8f166128ec79e2aa43d612cd9fd00b and 12f93027d90f2cbe7e27c4dd726dc80a8816631a?

**Comment by the-maldridge** [comment]
Yes, this was resolved in the linked commits.
