### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by the-maldridge** [BESTRobotics/registry#5]
@scauthen with the two of us working on this from effectively opposite ends, I think its probably pretty important that we use some kind of documentation around the API between the frontend and the backend.

What do you think about using OpenAPI specifications?

**Comment by scauthen** [comment]
I am good with this.

**Comment by the-maldridge** [comment]
I am following this standard for now: https://www.restapitutorial.com/lessons/httpmethods.html

I probably should write the actual openapi spec, but the file format for it is somewhat confusing to me at the moment, so I may just generate it from the finished server.
